{{- if .Values.route.enabled -}}
{{- $appName := include "general-template.name" . -}}
{{- $fullName := include "general-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  # Full name may cause hostname to extend beyond 63 characters
  # .spec.subdomain doesn't work so we must rely on hostname auto-generation from resource name
  name: {{ $appName }}
  # name: {{ $appName }}-{{ .Release.Namespace }}
  labels:
    {{- include "general-template.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  path: /
  to:
    kind: Service
    name: {{ $appName }}
    # name: {{ $fullName }}
  port:
    targetPort: {{ $svcPort }}
  
  {{- if .Values.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}

{{- end }}

