apiVersion: monitoring.coreos.com/v1 
kind: ServiceMonitor
metadata:
  name: {{ include "general-template.fullname" . }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      {{- include "general-template.selectorLabels" . | nindent 6 }}




